export type Locale = "en" | "es";

export const UI_COPY = {
  en: {
    eyebrow: "Treasury Resource Center",
    servicesTitle: "Treasury services",
    startOver: "Start over",
    welcomeTitle:
      "An interactive conversational guide for your Treasury services",
    welcomeBody:
      "This demo focuses on Truist One View. Choose that quick action below, or type your own question. Other topics are shown for demo context only.",
    quickActions: "Quick actions",
    demoNote:
      "Demo only — Truist One View is available. Other topics are shown for context and are not clickable in this demo.",
    nextSteps: "Next steps",
    you: "You",
    guide: "Guide",
    askLabel: "Ask a question",
    placeholder: "Ask about One View sign-in, mobile, admin…",
    send: "Send",
    attribution: (year: number) =>
      `Results generated by Claude. © ${year} Treasury Resource Center demo.`,
    languageLabel: "Language",
    disabledTitle: "Demo only — not available in this preview",
  },
  es: {
    eyebrow: "Centro de Recursos de Tesorería",
    servicesTitle: "Servicios de tesorería",
    startOver: "Empezar de nuevo",
    welcomeTitle:
      "Una guía conversacional interactiva para tus servicios de Tesorería",
    welcomeBody:
      "Esta demo se centra en Truist One View. Elige esa acción rápida abajo, o escribe tu propia pregunta. Los demás temas se muestran solo como contexto y no se pueden seleccionar en esta demo.",
    quickActions: "Acciones rápidas",
    demoNote:
      "Solo demo — Truist One View está disponible. Los demás temas se muestran como contexto y no se pueden seleccionar.",
    nextSteps: "Siguientes pasos",
    you: "Tú",
    guide: "Guía",
    askLabel: "Haz una pregunta",
    placeholder: "Pregunta sobre inicio de sesión, móvil, admin…",
    send: "Enviar",
    attribution: (year: number) =>
      `Resultados generados por Claude. © ${year} Demo del Centro de Recursos de Tesorería.`,
    languageLabel: "Idioma",
    disabledTitle: "Solo demo — no disponible en esta vista previa",
  },
} as const;

export function languageSystemInstruction(locale: Locale): string {
  if (locale === "es") {
    return [
      "Language requirement:",
      "- Respond entirely in clear, natural Spanish (neutral Latin American Spanish is fine).",
      "- Keep product names like Truist One View in English when that is the official name.",
      "- Keep replies short and easy to understand.",
      "- Do not include English except for official product names, emails, URLs, or code-like identifiers.",
    ].join("\n");
  }

  return [
    "Language requirement:",
    "- Respond entirely in clear, natural English.",
    "- Keep replies short and easy to understand.",
  ].join("\n");
}
